### ISSUE TITLE
al_income.yml can't get past `id: regular job employer` if `x.is_self_employed`

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-ALToolbox#141]
"Interview order" for ALJob won't get past `id: regular job employer` if user selects that they are self-employed.

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/main/docassemble/ALToolbox/data/questions/al_income.yml#L627

I think it'll be the same for ALItemizedJob.

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blob/main/docassemble/ALToolbox/data/questions/al_income.yml#L158

Can't ask for `x.employer.name.first` because that may not be filled in

[Also, how many of those questions need to be required? For example, does the postal code and phone need to be required?]

**Comment by BryceStevenWilley** [comment]
I'm gonna mention this is the docs, but the reason for this is mentioned right above the line you linked for ALItemizedJob;
```python
# NOTE: if `is_self_employed`, you need to set this yourself
```
Because in `al_income`, we only have access to the ALJob types. We need that job to be associated with some individual for us to actually be able to do anything with `is_self_employed` and the employer's name, which nothing in this module is.

In the ALAffidavit, the block that solves this is:
```yml
sets:
  - x.jobs[i].employer.name.first
generic object: ALIndividual
code: |
  if x.jobs[i].is_self_employed:
    x.jobs[i].employer.address = x.address
    x.jobs[i].employer.phone = x.phone_number
    x.jobs[i].employer.name = x.name
```

Definitely not great, but there's not a good way around it IMO. Unless you have any ideas.

> Can't ask for `x.employer.name.first` because that may not be filled in

That's explicitly why we define it right there; because it might not be filled in, we need to trigger a different code block (that needs to be provided by the user of this library) to fill it in when `is_self_employed == True`

> how many of those questions need to be required? For example, does the postal code and phone need to be required?

Those are required for the Massachusetts form, and I'd guess that they'd be required elsewhere as well. Is replacing that screen not a good trade off there? Those attributes aren't defined in the code blocks, unlike the employer name.

**Comment by plocket** [comment]
I think I didn't describe the problem clearly enough. When a user reaches the screen I named, there's an option to check off that they are self employed. If they select that option, they cannot move on to the next question. Either we can't ask about self employment on the same page as the employer name or we need some other solution.

**Comment by BryceStevenWilley** [comment]
I'm not sure which file you are using for testing, but again, it's because users need to add a code block that sets `x.employer.name.first`, and that's noted in the file (and will be documented in the documentation). Adding that code block above in a user's file would fix it.

In case you were trying the demo (which I hadn't done a through fix on when updating the rest of the module), I fixed it in #145, if you want to try that out.

**Comment by BryceStevenWilley** [comment]
We had a quick conversation about this, and can be summarized as:
* we should add a code block to AssemblyLine to make it easier for most of our users to have things work out of the box. Something like this:
   ```yml
   sets:
     - x.jobs[i].employer.name.first
   generic object: ALIndividual
   code: |
     if x.jobs[i].is_self_employed:
       x.jobs[i].employer.address = x.address
       x.jobs[i].employer.phone = x.phone_number
       x.jobs[i].employer.name = x.name
   ```
* if we can, the default code block in the demo, which sets just the employer's first name to "self-employed" and everything else to empty strings, might be a good default to just include in `al_income.yml` itself. We should see if that is actually a good default to have.
  * if not, we will document heavily in the file how to override that behavior.
