### ISSUE TITLE
When reviewing lists, shouldn't say "you've told us about" said thing

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALToolbox#148]
Happens currently if you are editing jobs, see below image:

![Text on the screen: "What is your job title? You've already told us about Cashier". Cashier is pre-filled in a field called "Job name"](https://user-images.githubusercontent.com/6252212/215119218-5e5fe54c-d3bc-48a3-a0f7-c073f4e0baba.png)

Happens because it's a check for `len(x.complete_elements()) > 0` on the list. Not sure if it'll work but my best attempt at fixing now would be 

```mako
% if len(x.complete_elements()) > 0`
You've already told about ${ comma_and([item for idx, item in enumerate(x.complete_elements()) if idx != i ]) } 
% endif
```

Needs to go in several places though, in this repo and maybe in docassemble-AssemblyLine as well.

**Comment by nonprofittechy** [comment]
I think a better fix is redefining the complete attribute for this list, no?

**Comment by BryceStevenWilley** [comment]
That doesn't work unfortunately. This is currently the Edit table for ALJobs:

```yml
generic object: ALJobList
table: x.table
rows: x
columns:
  - Title: |
      row_item.source
  - Employer: |
      row_item.employer.name if hasattr(row_item.employer.name, "first") else ""
  - Annual Income: |
      currency(row_item.gross_total())
edit:
  - source
  - employer.name.first
  - value
confirm: True
```

If we add `- complete`, the complete attribute, at the beginning of the `edit:` list, the only thing that happens is that it re-runs the code block that sets complete, which I think it just gets through without exception, since all of the other values are already set. You end up at the same screen with the same issue, and the `complete` variable is still set to true. There's no way to reconsider the complete attribute for the list items and all of their other values at the same time from the table that I can tell.
