### ISSUE TITLE
Remove the double scroll bar....pretty please.

### ISSUE THREAD

**Issue by ladracer** [SuffolkLITLab/docassemble-ALToolbox#179]
question: |
 Select your ${ ordinal(i) } document.
subquestion: |
 Start typing to find the ${ ordinal(i) } document you want to create.
fields:
 - Search: selected_templates[i].template
   input type: ajax
   action: template_filter
   trigger at: 2
under: |
 ${ display_template(collapse_all_templates, scrollable=True, collapse=False) }

![double scroll bar issue](https://github.com/SuffolkLITLab/docassemble-ALToolbox/assets/40646388/2995d897-82b0-4880-a4a9-0c612f3dcfeb)

Jonathan Pyle
  [1 hour ago](https://docassemble.slack.com/archives/C7791ATUJ/p1685123987135499?thread_ts=1685108818.974449&cid=C7791ATUJ)
It looks like that function was written by purplesky2016 on GitHub but I'm not sure who that is. Maybe 
[@Quinten Steenhuis](https://docassemble.slack.com/team/U78UWL07L)
 knows. There is probably a way to make the right-hand scroll bar disappear using CSS.

Quinten Steenhuis
  [1 hour ago](https://docassemble.slack.com/archives/C7791ATUJ/p1685124108382449?thread_ts=1685108818.974449&cid=C7791ATUJ)
[@Michael Koch](https://docassemble.slack.com/team/U018K83F9G8)
 you should open a bug on ALToolbox. I'm not sure if it's specific to your CSS theme though

Quinten Steenhuis
  [1 hour ago](https://docassemble.slack.com/archives/C7791ATUJ/p1685124126512769?thread_ts=1685108818.974449&cid=C7791ATUJ)
[@Michelle B](https://docassemble.slack.com/team/UHCKKPY3D)
 has been doing some bug fixing on that repo recently

**Comment by plocket** [comment]
I think I need a link to this code to troubleshoot. It's not a problem we've seen in our code, maybe because we haven't tried to put a table in a collapse template before. It would be most helpful to see the whole repo if possible, but if not then at least the full files where this code and related code exists.

**Comment by ladracer** [comment]
Michelle,

Good to hear from you.

Here is the code snippet that I think is this issue.

----------------------

---



id: select a document

progress: 0

question: |

  Select your ${ ordinal(i) } document.

subquestion: |

  You can create up to **three** documents simultaneously.



  Simply start typing to find the ${ ordinal(i) } document you want to
create.



fields:

  - Search: selected_templates[i].template

    input type: ajax

    action: template_filter

    trigger at: 3

under: |

  ${ display_template(collapse_all_templates, scrollable=True,
collapse=False) }

section: section_choose_templates



---



template: collapse_all_templates

subject: |

  Scroll to view available documents.

content: |

  ${ all_templates_table }



---



table: selected_templates.table

rows: |

  selected_templates.complete_elements()

columns:

  - Name: |

      nice_template_name(row_item.template) if hasattr(row_item,
"template") else "not yet defined"

  #- Fields: |

  #
 f'{len(DAStaticFile(filename=f"data/templates/{row_item.template}").get_docx_variables())}
fields'

edit:

  - template

delete buttons: True



---


Michael Koch

**Comment by plocket** [comment]
Copying the code and adding syntax:

```yml
---
id: select a document
progress: 0
question: |
  Select your ${ ordinal(i) } document.
subquestion: |
  You can create up to **three** documents simultaneously.
  Simply start typing to find the ${ ordinal(i) } document you want to
create.
fields:
  - Search: selected_templates[i].template
    input type: ajax
    action: template_filter
    trigger at: 3
under: |
  ${ display_template(collapse_all_templates, scrollable=True,
collapse=False) }
section: section_choose_templates
---
template: collapse_all_templates
subject: |
  Scroll to view available documents.
content: |
  ${ all_templates_table }
---
table: selected_templates.table
rows: |
  selected_templates.complete_elements()
columns:
  - Name: |
      nice_template_name(row_item.template) if hasattr(row_item,
"template") else "not yet defined"
  #- Fields: |
  #
 f'{len(DAStaticFile(filename=f"data/templates/{row_item.template}").get_docx_variables())}
fields'
edit:
  - template
delete buttons: True
---
```
