### ISSUE TITLE
Three Part Date: TypeError `get_$original_date(...).attr(....)` is undefined

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALToolbox#244]
> Exception occurred when checking element _ignore_Y2hpbGRyZW5baV0uYmlydGhkYXRl_year, check the 'alMax' method.

From the user's perspective, if you type a date that is before the min, the error message never goes away.

Looks like the specific line it's failing on is: 

```js
let max_date = new Date(get_$original_date(field).attr('data-alMax').replace(/-/g, '/'));.
```

https://github.com/SuffolkLITLab/docassemble-ALToolbox/blame/main/docassemble/ALToolbox/ThreePartsDate.py#L541

I don't have an `alMax` specified, which is likely the issue; it's assuming on will be there.

Running on latest `main`, with this question:

```yaml
id: minor birthdate question
question: |
  When was ${ children[i] } born?
fields:
  - Birthdate: children[i].birthdate
    datatype: BirthDate
    alMin: ${ format_date( today() - date_interval(years=18), format='MM/dd/yyyy') }
    alMinMessage: |
      This form is only for children under 18, but you said ${ children[i].name.familiar() } was over 18.
      Either correct the birth date, or ${ MLH_back_button_label.lower() } and add a different child under 18.
```
