### ISSUE TITLE
Can't edit number of hours worked in a job

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-ALToolbox#309]
The jobs table looks like this:

```yaml
generic object: ALItemizedJobList
table: x.table
rows: x
columns:
  - Title: |
      row_item.source
  - Employer: |
      row_item.employer.name if hasattr(row_item.employer.name, "first") else ""
  - Annual Gross Income: |
      currency(row_item.gross_total())
  - Annual Deductions: |
      currency(row_item.deduction_total())
edit:
  - source
  - employer.name.first
  - to_add.revisit
  - to_subtract.revisit
confirm: True
```
And doesn't take you to a page that can edit the number of hours worked.
